version: '3'
services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  voting-session-manager:
    image: voting-session-manager
    ports:
      - 8080:8080
    depends_on:
      - mongodb