spring:
  application:
    name: voting-session-manager
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/voting_session_db

server:
  port: 8080

cpf_validator:
  url: https://user-info.herokuapp.com